[base]
method = "exchange"
dimension = 3
label_list = ["z1", "z2", "z3"]
string_list = ["value_01", "value_02", "value_03" ]
degree_max = 7.0

[experiment]
path = "experiment.txt"
first = 1
last = 70

[file]
calculated_first_line = 5
calculated_last_line = 74
row_number = 2

[param]
min_list = [0.0, 0.0, 0.0]
max_list = [10.0, 10.0, 10.0]
numsteps = 1000
numsteps_exchange = 20
Tmin = 0.01
Tmax = 1.0
Tlogspace = false
seed = 12345
