[Main]
output_file_head = "surf_bulk_new111_ext"
[Main.algorithm]
algorithm = "minsearch"
[Main.param]
z_margin = 0.001
slab_margin = 10.0
r_SiH = 1.48 #angstrom
theta = 109.5 #H-Si-H angle in degre
[Main.lattice]
unit_vec = [[4.000668747, 0.00000, 0.00000], [0.00000, 4.000668747, 0.00000]]
[ASE]
solver_name = "qe"
kpts = [3,3,1]        # sampling k points (Monkhorst-Pack grid)
command = "mpirun -np 4 ./pw.x -in espresso.pwi > espresso.pwo"
[Solver]
[Solver.control]
calculation='bands' # 'scf','relax','bands',...
pseudo_dir='./'     # Pseudopotential directory
[Solver.system]
ecutwfc = 20.0        # Cut-off energy in Ry
nbnd = 33           # # of bands (only used in band structure calc
[Solver.pseudo]
Si = 'Ge.pbe-mt_fhi.UPF'
H = 'H.pbe-mt_fhi.UPF'
