[base]
dimension = 3
output_dir = "output"

[algorithm]
name = "exchange"
seed = 12345

[algorithm.param]
min_list = [-5, -5, -5]
max_list = [5, 5, 5]
unit_list = [0.01, 0.01, 0.01]

[algorithm.exchange]
numsteps = 5000
numsteps_exchange = 500
Tmin = 0.01
Tmax = 10
Tlogspace = false

[solver]
name = "analytical"
function_name = "liner_regression_test"
