name: deploy

on:
  push:
    tags: ['*']

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Publish
      working-directory: ${{ runner.workspace }}
      run: poetry publish --build -u yomichi -p "${{ secrets.PYPI_TOKEN }}"
