name: Test

on: [push]

jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6]
        algorithm: [mapper, minsearch, exchange]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: apt
        run: sudo apt install openmpi-bin libopenmpi-dev

      - name: pip
        run: |
          python -m pip install -U pip
          python -m pip install setuptools wheel
          python -m pip install numpy scipy toml mpi4py

      - name: TRHEPD
        run: |
          cd src/TRHEPD
          make

      - name: ${{ matrix.algorithm }}
        run: |
          cd ${GITHUB_WORKSPACE}/sample/original/${{ matrix.algorithm }}
          sh ./do.sh
